@API_HostAddress = http://localhost:5101/api
@shoppingCartId = 2bcc663e-cfca-4f5c-8b48-79aabdf4d55a
@iPhoneProductId = 9725e051-a46e-4c6e-a0f6-b1d476fef590
@macbookProProductId = 8d644e25-0ee5-4710-84ff-0cae051597e5
@customerId = 6b50d3c2-d155-4315-b0b2-427e69a41322

### POST Open shopping cart
POST {{API_HostAddress}}/shopping-carts
Content-Type: application/json

{
  "customerId": "{{customerId}}"
}

###

### POST Add iPhone to cart
POST {{API_HostAddress}}/shopping-carts/{{shoppingCartId}}/products
Content-Type: application/json

{
  "productId": "{{iPhoneProductId}}",
  "quantity": 1
}

###

### POST Add Macbook Pro to cart
POST {{API_HostAddress}}/shopping-carts/{{shoppingCartId}}/products
Content-Type: application/json

{
  "productId": "{{macbookProProductId}}",
  "quantity": 1
}

###

### GET Get shopping cart summary
GET {{API_HostAddress}}/shopping-carts/{{shoppingCartId}}
Content-Type: application/json

###

### PUT Confirm/checkout a shopping cart
PUT {{API_HostAddress}}/shopping-carts/{{shoppingCartId}}/confirm
Content-Type: application/json

###