@API_HostAddress = http://localhost:5101
@shoppingCartId = f74706ee-07a3-4182-b8c3-0d23930ce97c

POST {{API_HostAddress}}/api/shopping-carts
Accept: application/json
Content-Type: application/json

{
  "customerId": "2F1C5229-C75C-4D55-85F7-F57B43682078"
}
###

POST {{API_HostAddress}}/api/shopping-carts/{{shoppingCartId}}/products
Content-Type: application/json

{
  "productId": "76BE116D-8D94-4C36-9504-C49B440FBBD8",
  "quantity": 3
}

###
GET {{API_HostAddress}}/api/shopping-carts/{{shoppingCartId}}